apiVersion: v1
kind: Secret
metadata:
  name: jupyterhub-secret
  labels:
    app: jupyterhub
    tier: frontend
    environment: development
type: Opaque
stringData:
  JUPYTERHUB_ADMIN_USER: "admin"
  JUPYTERHUB_ADMIN_PASSWORD: "secure_admin_pass"
  JUPYTERHUB_SECRET_TOKEN: "my_super_secret_token_12345"

