apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
    tier: cache
    environment: development
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: redis-port
  selector:
    app: redis

